<?php
$z[0]=Array("channel","\r\n    \r\n    -<a href=\"[field:typeurl/]\" title=\"[field:typename/]\" >[field:typename/]</a>",94,222);
$z[0][4]['type']="top";
$z[1]=Array("global","",258,284);
$z[1][4]['name']="cfg_powerby";
$z[2]=Array("global","",299,323);
$z[2][4]['name']="cfg_beian";
$z[3]=Array("global","",352,373);
$z[3][4]['name']="cfg_dz";
$z[4]=Array("global","",408,429);
$z[4][4]['name']="cfg_dh";
$z[5]=Array("global","",432,453);
$z[5][4]['name']="cfg_yx";

?>