<?php
$z[0]=Array("global","",50,71);
$z[0][4]['name']="cfg_gg";
$z[1]=Array("type","<a href=\"[field:typelink/]\" title=\"[field:typename/]\">[field:typename/]</a>",104,211);
$z[1][4]['typeid']="1";
$z[2]=Array("type","<a href=\"[field:typelink/]\" title=\"[field:typename/]\">[field:typename/]</a>",220,327);
$z[2][4]['typeid']="2";
$z[3]=Array("field","(@me==\"\")? @me=\" class='libh linob' \":@me=\"\";",494,589);
$z[3][4]['name']="typeid";
$z[3][4]['runphp']="yes";
$z[4]=Array("channel","\r\n    <li><a href=\"[field:typeurl/]\" title=\"[field:typename/]\">[field:typename/]</a></li>\r\n    ",650,876);
$z[4][4]['type']="top";
$z[4][4]['currentstyle']="<li class='libh linob'><a href='~typelink~'>~typename~</a></li>";
$z[5]=Array("arclist","\r\n    <div class=\"slide\"><img src=\"[field:litpic/]\" width=\"1900\" height=\"488\" alt=\"[field:title/]\" title=\"[field:title/]\"/></div>\r\n    ",944,1123);
$z[5][4]['row']="3";
$z[5][4]['typeid']="6";

?>