<?php
$z[0]=Array("field","",141,163);
$z[0][4]['name']="typename";
$z[1]=Array("channel","\r\n        <dd><a href=\"[field:typelink/]\" title=\"[field:typename/]\">[field:typename/]</a></dd>\r\n        ",178,320);
$z[1][4]['type']="son";
$z[2]=Array("global","",541,562);
$z[2][4]['name']="cfg_dh";
$z[3]=Array("global","",629,650);
$z[3][4]['name']="cfg_yx";
$z[4]=Array("global","",678,699);
$z[4][4]['name']="cfg_dz";

?>